### PR TITLE
FIX: Overlay mode isn't applied via config file.

### PR DESCRIPTION
**Pull request by SaeGon-Heo**
If I drag & drop `config.kpsconf3` file on `KeysPerSecond-v8.4.exe` to run it with saved config which `Overlay mode` is `true`,
`Overlay mode` option is enabled but doesn't applied.
And this PR may fix this.

### CODE REVIEW

**Comment by RoanH** [comment]
Hey, thank you for the bug report and pull request. Nice job finding this bug. Your fix works properly, but the underlying issue is a bit more involved (honestly configuration files should be handled better, I'll get around to that someday). The stats saving is actually suffering from the exact same issue, for some reason I decided to manually manage the state of a few things even though I have a subroutine called reconfigure to do exactly that... And it seems like the manual managing did not work out for the overlay option and stats saving.

I'll push a few commits of my own to fix stats saving and then I'll merge this if you're fine with the changes I've made.

**Review by RoanH — APPROVED** [review]
I've made all the changes I wanted to make, if you're fine with the changes I made please approve or leave a comment and I'll merge this. Thanks again for contributing!

**Comment by SaeGon-Heo** [comment]
Looks cool. I didn't noticed reconfigure() function does at all :)
You may go with that. Thanks to patch a bug!

**Comment by RoanH** [comment]
Awesome, thanks for the contribution.

**Pull request merged**
